apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hocs-refresh-members-job
spec:
  schedule: "0 {{.MEMBER_REFRESH_HOUR}} * * *"
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            name: hocs-refresh-members-job
            role: hocs-backend
        spec:
          containers:
            - name: hocs-refresh-members-job
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
              image: quay.io/ukhomeofficedigital/hocs-base-image:latest
              env:
                - name: HOCS_BASICAUTH
                  valueFrom:
                    secretKeyRef:
                      name: ui-casework-creds
                      key: plaintext
              command: [ "/bin/sh", "-c" ]
              args:
                - http_status=$( wget --no-check-certificate --spider -S "https://${HOCS_BASICAUTH}@hocs-info-service.{{.KUBE_NAMESPACE}}.svc.cluster.local/admin/member/refresh" 2>&1 | grep "HTTP/" | awk '{print $2}' ); if [[ $http_status -eq 200 ]]; then exit 0; else exit 1; fi
          restartPolicy: OnFailure
