---
kind: pipeline
type: kubernetes
name: deploy
trigger:
  event:
    - promote
  target:
    exclude:
      - restart*

steps:
  - name: fetch and checkout
    image: alpine/git
    commands:
      - git fetch --tags
      - git checkout $${VERSION}

  - name: deploy to cs-qa
    image: quay.io/ukhomeofficedigital/kd
    environment:
      ENVIRONMENT: cs-qa
      KUBE_TOKEN:
        from_secret: hocs_info_service_cs_qa
    commands:
      - cd kube
      - ./deploy.sh
    depends_on:
      - fetch and checkout
    when:
      target:
        - release

  - name: deploy to wcs-qa
    image: quay.io/ukhomeofficedigital/kd
    environment:
      ENVIRONMENT: wcs-qa
      KUBE_TOKEN:
        from_secret: hocs_info_service_wcs_qa
    commands:
      - cd kube
      - ./deploy.sh
    depends_on:
      - fetch and checkout
    when:
      target:
        - release

  - name: deployment to not-prod
    image: quay.io/ukhomeofficedigital/kd
    environment:
      ENVIRONMENT: ${DRONE_DEPLOY_TO}
      KUBE_TOKEN:
        from_secret: hocs_info_service_${DRONE_DEPLOY_TO/-/_}
    commands:
      - cd kube
      - ./deploy.sh
    depends_on:
      - fetch and checkout
    when:
      target:
        exclude:
          - release
          - "*-prod"

  - name: deploy to prod
    image: quay.io/ukhomeofficedigital/kd
    environment:
      ENVIRONMENT: ${DRONE_DEPLOY_TO}
      KUBE_TOKEN:
        from_secret: hocs_info_service_${DRONE_DEPLOY_TO/-/_}
    commands:
      - cd kube
      - ./deploy.sh
    depends_on:
      - fetch and checkout
    when:
      target:
        - "*-prod"

---
kind: pipeline
type: kubernetes
name: tag data
trigger:
  event:
    - tag
  branch:
    - main
clone:
  disable: true

steps:
  - name: env-file
    image: alpine:latest
    commands:
      - echo HOCS_INFO_SERVICE_DATA_VERSION=$${DRONE_TAG} > info-service-data-version.env

  - name: CS downstream build
    image: plugins/downstream
    settings:
      server: https://drone-gh.acp.homeoffice.gov.uk
      deploy: cs-qa
      fork: false
      last_successful: true
      token:
        from_secret: DRONE_TOKEN
      params:
        - info-service-data-version.env
      repositories:
        - UKHomeOffice/hocs-data@main
    depends_on:
      - env-file

  - name: WCS downstream build
    image: plugins/downstream
    settings:
      server: https://drone-gh.acp.homeoffice.gov.uk
      deploy: wcs-qa
      fork: false
      last_successful: true
      token:
        from_secret: DRONE_TOKEN
      params:
        - info-service-data-version.env
      repositories:
        - UKHomeOffice/hocs-data-wcs@main
    depends_on:
      - env-file

---
kind: pipeline
type: kubernetes
name: deploy tag
trigger:
  event:
    - tag
  branch:
    - main
depends_on:
  - tag data

steps:
  - name: deploy to cs-dev
    image: quay.io/ukhomeofficedigital/kd
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: cs-dev
      KUBE_TOKEN:
        from_secret: hocs_info_service_cs_dev
      KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      VERSION: "${DRONE_TAG}"
    depends_on:
      - clone

  - name: deploy to wcs-dev
    image: quay.io/ukhomeofficedigital/kd
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: wcs-dev
      KUBE_TOKEN:
        from_secret: hocs_info_service_wcs_dev
      KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      VERSION: "${DRONE_TAG}"
    depends_on:
      - clone
