---
kind: pipeline
type: kubernetes
name: tag data
trigger:
  event:
    - tag
  branch:
    - main

clone:
  disable: true

steps:
  - name: env-file
    image: alpine:latest
    commands:
      - echo HOCS_INFO_SERVICE_DATA_VERSION=$${DRONE_TAG} > info-service-data-version.env

  - name: CS downstream build
    image: plugins/downstream
    settings:
      server: https://drone-gh.acp.homeoffice.gov.uk
      deploy: cs-qa
      fork: false
      last_successful: true
      token:
        from_secret: DRONE_TOKEN
      params:
        - info-service-data-version.env
      repositories:
        - UKHomeOffice/hocs-data@main
    depends_on:
      - env-file

  - name: WCS downstream build
    image: plugins/downstream
    settings:
      server: https://drone-gh.acp.homeoffice.gov.uk
      deploy: wcs-qa
      fork: false
      last_successful: true
      token:
        from_secret: DRONE_TOKEN
      params:
        - info-service-data-version.env
      repositories:
        - UKHomeOffice/hocs-data-wcs@main
    depends_on:
      - env-file
---
kind: pipeline
type: kubernetes
name: deploy tag
trigger:
  event:
    - tag
  branch:
    - main
depends_on:
  - tag data
concurrency:
  limit: 1

steps:
  - name: checkout
    image: quay.io/ukhomeofficedigital/hocs-helm-kubectl:1.1.0
    commands:
      - git fetch --tags
      - git checkout ${DRONE_TAG}
      - git submodule update --init --recursive

  - &deploy
    name: cs-dev
    image: quay.io/ukhomeofficedigital/hocs-helm-kubectl:1.1.0
    environment:
      CHART_NAME: hocs-info-service
      CHART_VERSION: ^2.0.0
      KUBE_CLUSTER: acp-notprod
      KUBE_NAMESPACE: cs-dev
      KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      KUBE_TOKEN:
        from_secret: cs_notprod
      VERSION: ${DRONE_TAG}
    commands:
      - ./ci/helm/helm-chart-deploy.sh --values ./helm/hocs-info-service.yaml
    depends_on:
      - checkout

  - <<: *deploy
    name: wcs-dev
    environment:
      KUBE_NAMESPACE: wcs-dev
    commands:
      - ./ci/helm/helm-chart-deploy.sh --values ./helm/hocs-info-service.yaml --values ./helm/hocs-info-service-wcs.yaml
    depends_on:
      - cs-dev
