pipeline:

  wait-for-keycloak:
    image: quay.io/ukhomeofficedigital/hocs-docker-tools:build-4
    commands:
    - |
      until $(curl --output /dev/null --silent --head --fail http://keycloak:8080/auth/realms/master/.well-known/openid-configuration); do
        echo "waiting for keycloak"
        sleep 5
      done
    - |
      export TKN=$(curl -X POST 'http://keycloak:8080/auth/realms/master/protocol/openid-connect/token' -H "Content-Type: application/x-www-form-urlencoded" -d "username=admin" -d 'password=password1' -d 'grant_type=password' -d 'client_id=admin-cli' | jq -r '.access_token')
    - |
      curl -vX POST http://keycloak:8080/auth/admin/realms -d @keycloak/local-realm.json --header "Authorization: Bearer $TKN" --header "Content-Type: application/json"

  build-project:
    image: quay.io/ukhomeofficedigital/openjdk11:v11.0.5_10
    commands:
      - export SPRING_PROFILES_ACTIVE='development, local, test'
      - export DB_HOST='postgres'
      - export KEYCLOAK_SERVER_ROOT=http://keycloak:8080
      - export AWS_LOCAL_HOST='localstack'
      - ./gradlew build --no-daemon
    when:
      event: [push, pull_request, tag]

  sonar-scanner:
    image: quay.io/ukhomeofficedigital/sonar-scanner:v3.0.2
    when:
      event: [push, pull_request, tag]

  docker-build:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t hocs-info-service .
    when:
      branch: master
      event: [push, tag]

  install-docker-image:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+hocs" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag hocs-info-service quay.io/ukhomeofficedigital/hocs-info-service:build-$${DRONE_BUILD_NUMBER}
      - docker tag hocs-info-service quay.io/ukhomeofficedigital/hocs-info-service:latest
      - docker push quay.io/ukhomeofficedigital/hocs-info-service:build-$${DRONE_BUILD_NUMBER}
      - docker push quay.io/ukhomeofficedigital/hocs-info-service:latest
    when:
      branch: master
      event: [push]

  docker-semver-tag:
    image: quay.io/ukhomeofficedigital/hocs-version-bot:build-25
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - DOCKER_API_VERSION=1.37
    secrets:
      - github_password
      - docker_password
      - git_password
    commands:
      - /app/hocs-deploy --version=$${SEMVER} --serviceGitToken=$${GIT_PASSWORD} --service=hocs-info-service --gitToken=$${GITHUB_PASSWORD} --gitRepo="https://gitlab.digital.homeoffice.gov.uk/hocs/hocs-versions.git" --environment=qa --dockerRepository=quay.io/ukhomeofficedigital --sourceBuild=$${IMAGE_VERSION} --registryUser=ukhomeofficedigital+hocs --registryPassword=$${DOCKER_PASSWORD}
    when:
      event: deployment
      environment: [cs-qa, wcs-qa]

  generate-dot-env-file-for-hocs-data-image-build-steps:
    image: alpine:latest
    commands:
      - source version.txt
      - echo HOCS_INFO_SERVICE_DATA_VERSION=$VERSION > info-service-data-version.env
    when:
      event: deployment
      environment: [cs-qa, wcs-qa]

  trigger_hocs_data_build_with_semver_tag:
    image: plugins/downstream
    server: https://drone-gh.acp.homeoffice.gov.uk
    fork: true
    token: ${DRONE_TOKEN}
    secrets:
      - drone_token
    params:
      - info-service-data-version.env
    repositories:
      - UKHomeOffice/hocs-data
    when:
      event: deployment
      environment: [cs-qa]

  trigger_hocs_data_wcs_build_with_semver_tag:
    image: plugins/downstream
    server: https://drone-gh.acp.homeoffice.gov.uk
    fork: true
    token: ${DRONE_TOKEN}
    secrets:
      - drone_token
    params:
      - info-service-data-version.env
    repositories:
      - UKHomeOffice/hocs-data-wcs
    when:
      event: deployment
      environment: [wcs-qa]

  clone-kube-project:
    image: plugins/git
    commands:
      - git clone https://github.com/UKHomeOffice/kube-hocs-info-service.git
    when:
      event: [push, tag, deployment]

  deploy-to-cs-dev-from-build-number:
    group: deploy-to-dev
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    environment:
      - ENVIRONMENT=cs-dev
      - VERSION=build-${DRONE_BUILD_NUMBER}
      - HOCS_INFO_SERVICE_DATA_VERSION=latest
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - hocs_info_service_dev_cs
    commands:
      - cd kube-hocs-info-service
      - ./deploy.sh
    when:
      branch: master
      event: [push, tag]

  deploy-to-wcs-dev-from-build-number:
    group: deploy-to-dev
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    environment:
      - ENVIRONMENT=wcs-dev
      - VERSION=build-${DRONE_BUILD_NUMBER}
      - HOCS_INFO_SERVICE_DATA_VERSION=latest
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - hocs_info_service_dev_wcs
    commands:
      - cd kube-hocs-info-service
      - ./deploy.sh
    when:
      branch: master
      event: [push, tag]

  deployment:
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    environment:
      - ENVIRONMENT=${DRONE_DEPLOY_TO}
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - hocs_info_service_dev_cs
      - hocs_info_service_demo_cs
      - hocs_info_service_dev_wcs
      - hocs_info_service_demo_wcs
    commands:
      - cd kube-hocs-info-service
      - ./deploy.sh
    when:
      event: deployment
      environment: [cs-dev, cs-demo, wcs-dev, wcs-demo]

  deploy-to-qa-cs:
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    environment:
      - ENVIRONMENT=cs-qa
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - hocs_info_service_qa_cs
    commands:
      - source version.txt
      - echo $VERSION
      - cd kube-hocs-info-service
      - ./deploy.sh
    when:
      event: deployment
      environment: cs-qa

  deploy-to-qa-wcs:
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    environment:
      - ENVIRONMENT=wcs-qa
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - hocs_info_service_qa_wcs
    commands:
      - source version.txt
      - echo $VERSION
      - cd kube-hocs-info-service
      - ./deploy.sh
    when:
      event: deployment
      environment: wcs-qa

  deploy-to-prod-cs:
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    environment:
      - ENVIRONMENT=cs-prod
      - KUBE_SERVER=https://kube-api-prod.prod.acp.homeoffice.gov.uk
    secrets:
      - hocs_info_service_prod_cs
    commands:
      - cd kube-hocs-info-service
      - ./deploy.sh
    when:
      event: deployment
      environment: cs-prod

  deploy-to-prod-wcs:
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    environment:
      - ENVIRONMENT=wcs-prod
      - KUBE_SERVER=https://kube-api-prod.prod.acp.homeoffice.gov.uk
    secrets:
      - hocs_info_service_prod_wcs
    commands:
      - cd kube-hocs-info-service
      - ./deploy.sh
    when:
      event: deployment
      environment: wcs-prod

services:

  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password1
      DB_VENDOR: h2

  postgres:
    image: quay.io/ukhomeofficedigital/postgres-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev
