package uk.gov.digital.ho.hocs.info.application;

public enum LogEvent {
    UNIT_CREATED,
    UNIT_NOT_FOUND,
    UNIT_RETRIEVED,
    UNIT_DELETED,
    TEAM_CREATED,
    FAILED_TO_CREATE_TEAM,
    FAILED_TO_PATCH_TEAM,
    TEAM_ADDED_TO_UNIT,
    TEAM_RENAMED,
    TEAM_ACTIVE_FLAG_SET,
    TEAM_DELETED,
    TEAM_DELETED_FAILURE,
    TEAM_PERMISSIONS_UPDATED,
    TEAM_PERMISSIONS_DELETED,
    USERS_ADDED_TO_TEAM,
    KEYCLOAK_FAILURE,
    UNCAUGHT_EXCEPTION,
    REST_HELPER_NOT_FOUND,
    REST_HELPER_INTERNAL_SERVER_ERROR,
    REST_HELPER_MALFORMED_RESPONSE,
    AUDIT_EVENT_CREATED,
    AUDIT_FAILED,
    USER_REMOVED_FROM_TEAM;
    public static final String EVENT = "event_id";
    public static final String EXCEPTION = "exception";
}
