package uk.gov.digital.ho.hocs.info.client.auditClient.dto;

public enum EventType {
    CREATE_CONSTITUENCY,
    REMOVE_CONSTITUENCY,
    REACTIVATE_CONSTITUENCY,
    CREATE_TEAM,
    RENAME_TEAM,
    DELETE_TEAM,
    ADD_USER_TO_TEAM,
    REMOVE_USER_FROM_TEAM,
    MOVE_TEAM_TO_UNIT,
    UPDATE_TEAM_PERMISSIONS,
    REMOVE_PERMISSIONS_FROM_TEAM,
    CREATE_TOPIC,
    CREATE_PARENT_TOPIC,
    REMOVE_TOPIC,
    REMOVE_PARENT_TOPIC,
    REACTIVATE_TOPIC,
    REACTIVATE_PARENT_TOPIC,
    UPDATE_TOPIC_PARENT,
    ADD_TEAM_TO_TOPIC,
    UPDATE_TEAM_FOR_TOPIC,
    CREATE_CORRESPONDENT_TYPE
    ;}