delete from parent_topic where true;
delete from team_link where true;
delete from topic where true;
delete from team_contact where true;
delete from correspondent_type where true;
delete from permission where true;
delete from exemption_date where true;
delete from case_type_schema where true;
delete from stage_type_schema where true;
delete from stage_type where true;
delete from team where true;
delete from case_type where true;
delete from unit where true;
delete from constituency;
delete from region;
