---
deployment:
  annotations:
    downscaler/downtime: "Sat-Sun 00:00-24:00 Europe/London,Mon-Fri 00:00-07:45 Europe/London,Mon-Fri 18:05-24:00 Europe/London"

data:
  enabled: true
  image:
    name: hocs-data

app:
  env:
    allowedDomains: 'digital.homeoffice.gov.uk,homeoffice.gov.uk,hmpo.gov.uk,cluster2security.gov.uk,combatingdrugs.gov.uk,gro.gov.uk'
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 512Mi

members:
  enabled: true
  refresh: '0 8 * * *'
