name: 'SemVer - Tag on Data Change'
on:
  workflow_dispatch:
    inputs:
      increment:
        description: 'SemVer Increment Value'
        required: true
        type: choice
        default: 'patch'
        options:
          - patch
          - minor
          - major

jobs:
  semver:
    name: Manual SemVer Tag
    runs-on: ubuntu-latest
    steps:
      - uses: UKHomeOffice/semver-tag-action@v2
        with:
          increment: ${{ github.event.inputs.increment }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_use_head_tag: true
      - name: Post failure to Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.19.0
        if: ${{ failure() && steps.*.conclusion == 'failure' }}
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: "GitHub Action failure: ${{github.repository}}\nRun: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}\nOriginating PR: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
