name: 'SemVer - Tag on Data Change'
on:
  workflow_dispatch:
    inputs:
      increment:
        description: 'SemVer Increment Value'
        required: true
        type: choice
        default: 'patch'
        options:
          - patch
          - minor
          - major

jobs:
  semver:
    name: 'Manual SemVer Tag'
    runs-on: ubuntu-latest
    steps:

      - name: Calculate SemVer increment
        id: increment
        uses: UKHomeOffice/semver-tag-action@v3
        with:
          increment: ${{ github.event.inputs.increment }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_use_head_tag: true
          dry_run: true

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT_USER_NAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Calculate metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.images }}
          tags: |
            type=raw,value=${{steps.increment.outputs.version}}
            type=raw,value=latest,enable=true

      - name: Build container
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Tag repository with SemVer
        uses: UKHomeOffice/semver-tag-action@v3
        with:
          tag: ${{steps.increment.outputs.version}}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_use_head_tag: true

      - name: Post failure to Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.21.0
        if: ${{ failure() && steps.*.conclusion == 'failure' }}
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: "GitHub Action failure: ${{github.repository}}\nRun: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}\nOriginating PR: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
